[package]
name = "graphvizm"
version = "0.1.0"
edition = "2024"
build = "build.rs"
include = [
  "src/",
  "vendor/viz.wasm",
  "vendor/world.wit",
  "build.rs",
  "Cargo.toml",
]

[dependencies]
anyhow = "1"
thiserror = "1.0"
wasmtime = "38.0.4"
wasmtime-wasi = "38.0.4"
